groups:
  ai:
    terms: ["ai","openai","chatgpt","gpt"]
    regex: ["gen\\s*ai","gpt-?\\d+"]
  semiconductor:
    terms: ["chip","chips","semiconductor","gpu","nvidia","tsmc","intel"]
  economy:
    terms: ["inflation","cpi","jobs","unemployment","gdp","rates","fed"]
  apple:
    terms: ["apple","iphone","ios","vision pro"]