name: archive-daily
on:
  schedule:
    - cron: "20 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: archive-daily
  cancel-in-progress: false

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Download latest warehouse artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: update-warehouse.yml
          workflow_conclusion: success
          branch: main
          path: artifacts
          if_no_artifact_found: fail

      - name: Restore warehouse
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data/warehouse/daily
          MASTER=$(find artifacts -type f -name master.jsonl | head -1)
          cp -v "$MASTER" data/warehouse/master.jsonl
          find artifacts -type f -path "*/daily/*.jsonl" -print0 | xargs -0 -I{} cp -v "{}" data/warehouse/daily/ || true

      - name: Compute date (UTC yesterday)
        id: when
        shell: bash
        run: |
          if date -u -d yesterday +%F >/dev/null 2>&1; then
            echo "date=$(date -u -d yesterday +%F)" >> "$GITHUB_OUTPUT"
          else
            echo "date=$(date -u -v-1d +%F)" >> "$GITHUB_OUTPUT"
          fi

      - name: Build daily file
        shell: bash
        env:
          D: ${{ steps.when.outputs.date }}
        run: |
          set -euo pipefail
          SRC="data/warehouse/daily/${D}.jsonl"
          OUT="data/warehouse/daily/news_${D}.jsonl"
          if [ -f "$SRC" ]; then
            cp -v "$SRC" "$OUT"
          else
            python - <<'PY'
import os, json, sys, pathlib
d=os.environ["D"]
src=pathlib.Path("data/warehouse/master.jsonl")
dst=pathlib.Path(f"data/warehouse/daily/news_{d}.jsonl")
cnt=0
with src.open("r", encoding="utf-8") as f, dst.open("w", encoding="utf-8") as out:
    for line in f:
        try:
            o=json.loads(line)
        except Exception:
            continue
        t=o.get("date") or o.get("publishedAt") or o.get("published_at") or ""
        if isinstance(t,str) and t.startswith(d):
            out.write(json.dumps(o, ensure_ascii=False)+"\n"); cnt+=1
print(f"rows={cnt}")
if cnt==0:
    sys.exit(2)
PY
          fi
          gzip -9f "$OUT"

      - name: Release snapshot
        uses: softprops/action-gh-release@v2
        with:
          tag_name: snap-${{ steps.when.outputs.date }}
          name: snap-${{ steps.when.outputs.date }}
          files: data/warehouse/daily/news_${{ steps.when.outputs.date }}.jsonl.gz
