name: archive-daily

on:
  schedule:
    - cron: "20 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: archive-daily
  cancel-in-progress: false

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Download latest warehouse artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: update-warehouse.yml
          workflow_conclusion: success
          branch: main
          path: artifacts
          if_no_artifact_found: fail

      - name: Restore warehouse
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data/warehouse/daily
          MASTER=$(find artifacts -type f -name master.jsonl | head -1)
          cp -v "$MASTER" data/warehouse/master.jsonl || exit 1
          find artifacts -type f -path "*/daily/*.jsonl" -print0 | xargs -0 -I{} cp -v "{}" data/warehouse/daily/ || true

      - name: Compute date (UTC yesterday)
        id: when
        run: |
          if date -u -d yesterday +%F >/dev/null 2>&1; then
            echo "date=$(date -u -d yesterday +%F)" >> "$GITHUB_OUTPUT"
          else
            echo "date=$(date -u -v-1d +%F)" >> "$GITHUB_OUTPUT"
          fi

      - name: Build daily file
        env:
          D: ${{ steps.when.outputs.date }}
        run: |
          set -euo pipefail
          SRC="data/warehouse/daily/${D}.jsonl"
          OUT="data/warehouse/daily/news_${D}.jsonl"
          if [ -f "$SRC" ]; then
            cp -v "$SRC" "$OUT"
          else
            jq -c --arg d "$D" 'select(((.date // .publishedAt // .published_at // "")|tostring) | startswith($d))' \
              data/warehouse/master.jsonl > "$OUT"
            ROWS=$(wc -l < "$OUT" | tr -d ' ')
            echo "rows=$ROWS"
            [ "${ROWS}" -gt 0 ] || exit 2
          fi
          gzip -9f "$OUT"

      - name: Release snapshot
        uses: softprops/action-gh-release@v2
        with:
          tag_name: snap-${{ steps.when.outputs.date }}
          name: snap-${{ steps.when.outputs.date }}
          files: data/warehouse/daily/news_${{ steps.when.outputs.date }}.jsonl.gz
