name: collect-live

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest
    env:
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .

      - name: Show clock
        run: |
          echo "UTC_NOW=$(date -u +"%F %T")"

      - name: Collect live (NewsAPI)
        if: env.NEWSAPI_KEY != ''
        env:
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        run: |
          set -e
          newscli collect-live \
            --recent-minutes 30 \
            --pages 2 \
            --query "news" \
            --outdir data/raw_newsapi

      - name: Skip collect (no NEWSAPI_KEY)
        if: env.NEWSAPI_KEY == ''
        run: echo "NEWSAPI_KEY not set; skipping."

      - name: Commit and push if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          CHANGES=$(git status --porcelain | wc -l)
          if [ "$CHANGES" -gt 0 ]; then
            git commit -m "live: append $(date -u +%F\ %H:%M)Z"
            git push
          else
            echo "no changes"
          fi

