name: entities-report
on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch: {}
permissions:
  contents: read
concurrency:
  group: repo-push
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pandas matplotlib
          pip install -e .
          python -m pip install spacy
          python -m spacy download en_core_web_sm
      - name: Ensure configs
        run: |
          mkdir -p config reports/entities
          [ -f config/entities_aliases.json ] || echo "{}" > config/entities_aliases.json
          [ -f config/entities_stopwords.txt ] || : > config/entities_stopwords.txt
          touch reports/entities/.gitkeep

      - name: Download latest warehouse artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: update-warehouse.yml
          workflow_conclusion: success
          name: ^warehouse-.*
          name_is_regexp: true
          path: artifacts
          if_no_artifact_found: warn

      - name: List downloaded artifacts
        run: |
          echo "::group::Artifacts tree"
          ls -Rla artifacts || true
          echo "::endgroup::"

      - name: Restore warehouse from artifact
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data/warehouse data/metrics

          FOUND=$(find artifacts -type f -path "*/data/warehouse/master.jsonl" | head -1 || true)
          if [ -z "${FOUND:-}" ]; then
            FOUND=$(find artifacts -type f -name "master.jsonl" | head -1 || true)
          fi

          if [ -n "${FOUND:-}" ]; then
            BASE=$(dirname "$FOUND")                # .../data/warehouse
            rsync -av "$BASE/" data/warehouse/
            MET=$(find artifacts -type d -path "*/data/metrics" | head -1 || true)
            if [ -n "${MET:-}" ]; then
              rsync -av "$MET/" data/metrics/
            fi
          fi

          if [ ! -f data/warehouse/master.jsonl ]; then
            echo "::error::No warehouse artifact found. Run 'update-warehouse' workflow first."
            exit 1
          fi

      - name: Extract entities
        run: |
          python scripts/entities_extract.py \
            --master data/warehouse/master.jsonl \
            --outdir reports/entities \
            --aliases config/entities_aliases.json \
            --stopwords config/entities_stopwords.txt \
            --model en_core_web_sm \
            --min-len 3

      - name: Render report
        run: |
          python scripts/entities_report.py \
            --daily-csv reports/entities/entities_daily.csv \
            --outdir reports/entities \
            --topk 30 --slope-days 30 --trend-days 60 --heat-top 20

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: entities-${{ github.run_id }}
          path: reports/entities/**
          retention-days: 14
