name: entities-report

on:
  schedule:
    - cron: "20 9 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: |
          python -m pip install --upgrade pip
          pip install pandas numpy matplotlib spacy
          python -m spacy download en_core_web_sm
      - name: Build entities daily
        run: |
          mkdir -p reports/entities config
          python scripts/entities_extract.py --master data/warehouse/master.jsonl --outdir reports/entities --aliases config/entities_aliases.json --stopwords config/entities_stopwords.txt --model en_core_web_sm --min-len 3 --days 0
      - name: Render report
        run: |
          python scripts/entities_report.py --daily-csv reports/entities/entities_daily.csv --outdir reports/entities --topk 30 --slope-days 30 --trend-days 60 --heat-top 20
      - name: Commit & push
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A reports/entities
          git commit -m "entities: update report $(date -u +%F)" || echo "no changes"
          git push

