name: entities-report
on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch: {}
permissions:
  contents: read
concurrency:
  group: repo-push
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pandas matplotlib
          pip install -e .
          python -m pip install spacy
          python -m spacy download en_core_web_sm

      - name: Ensure configs
        run: |
          mkdir -p config reports/entities
          [ -f config/entities_aliases.json ] || echo "{}" > config/entities_aliases.json
          [ -f config/entities_stopwords.txt ] || : > config/entities_stopwords.txt
          touch reports/entities/.gitkeep

      - name: Update warehouse (inline)
        run: |
          python scripts/update_corpus.py
          test -f data/warehouse/master.jsonl || (echo "missing data/warehouse/master.jsonl" && exit 1)

      - name: Extract entities
        run: |
          python scripts/entities_extract.py \
            --master data/warehouse/master.jsonl \
            --outdir reports/entities \
            --aliases config/entities_aliases.json \
            --stopwords config/entities_stopwords.txt \
            --model en_core_web_sm \
            --min-len 3

      - name: Render report
        run: |
          python scripts/entities_report.py \
            --daily-csv reports/entities/entities_daily.csv \
            --outdir reports/entities \
            --topk 30 --slope-days 30 --trend-days 60 --heat-top 20

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: entities-${{ github.run_id }}
          path: reports/entities/**
          retention-days: 14
