name: trend-site
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt

      - name: Build trends site
        run: |
          python scripts/aggregate_from_warehouse.py --warehouse data/warehouse/daily --out run --last-days 30
          python scripts/build_static_ui.py --run run --out site

      - name: Pull report artifact (optional)
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: entities-report.yml
          branch: main
          name: entities-site
          path: _report
        continue-on-error: true

      - name: Merge report into site
        run: |
          if [ -d _report ]; then
            mkdir -p site/report
            cp -r _report/* site/report/
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
