name: entities-report

on:
  workflow_dispatch:
  schedule:
    - cron: "25 7 * * *"

permissions:
  contents: read

concurrency:
  group: entities-report
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pandas numpy matplotlib

      - name: Download latest warehouse artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: update-warehouse.yml
          workflow_conclusion: success
          branch: main
          name: warehouse
          path: _wh
          if_no_artifact_found: fail

      - name: Restore warehouse
        run: |
          set -euo pipefail
          mkdir -p data/warehouse
          if [ -f _wh/artifact.tar ]; then
            tar -xf _wh/artifact.tar -C data/warehouse
          else
            cp -R _wh/* data/warehouse/ || true
          fi
          if [ -d data/warehouse/warehouse ]; then
            mv data/warehouse/warehouse/* data/warehouse/
            rmdir data/warehouse/warehouse || true
          fi
          test -d data/warehouse/daily

      - name: Build entities report
        run: |
          set -euo pipefail
          python scripts/entities_report.py \
            --warehouse data/warehouse/daily \
            --outdir site/entities \
            --topk 30 \
            --slope-days 30 \
            --trend-days 60 \
            --heat-top 20
          test -s site/entities/report.html

      - name: Upload artifact (report only, no deploy)
        uses: actions/upload-artifact@v4
        with:
          name: entities-report
          path: site/entities
          if-no-files-found: error
          retention-days: 7
